"""add_student_course_enrollments

Revision ID: 1db0219f8f7e
Revises: d5f8a9b2c341
Create Date: 2026-06-21 13:31:37.754358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db0219f8f7e'
down_revision: Union[str, Sequence[str], None] = 'd5f8a9b2c341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_course_enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority_override', sa.Integer(), nullable=True),
    sa.Column('personal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_student_course')
    )
    op.create_index(op.f('ix_student_course_enrollments_course_id'), 'student_course_enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_student_course_enrollments_id'), 'student_course_enrollments', ['id'], unique=False)
    op.create_index(op.f('ix_student_course_enrollments_status'), 'student_course_enrollments', ['status'], unique=False)
    op.create_index(op.f('ix_student_course_enrollments_user_id'), 'student_course_enrollments', ['user_id'], unique=False)
    op.drop_index('ix_audit_logs_entity_type_operation', table_name='audit_logs')
    op.drop_index('ix_audit_logs_entity_type_timestamp', table_name='audit_logs')
    op.drop_index('ix_audit_logs_user_id_timestamp', table_name='audit_logs')
    op.drop_index('ix_universities_name_is_deleted', table_name='universities')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_universities_name_is_deleted', 'universities', ['name', 'is_deleted'], unique=False)
    op.create_index('ix_audit_logs_user_id_timestamp', 'audit_logs', ['user_id', sa.text('timestamp DESC')], unique=False)
    op.create_index('ix_audit_logs_entity_type_timestamp', 'audit_logs', ['entity_type', sa.text('timestamp DESC')], unique=False)
    op.create_index('ix_audit_logs_entity_type_operation', 'audit_logs', ['entity_type', 'operation'], unique=False)
    op.drop_index(op.f('ix_student_course_enrollments_user_id'), table_name='student_course_enrollments')
    op.drop_index(op.f('ix_student_course_enrollments_status'), table_name='student_course_enrollments')
    op.drop_index(op.f('ix_student_course_enrollments_id'), table_name='student_course_enrollments')
    op.drop_index(op.f('ix_student_course_enrollments_course_id'), table_name='student_course_enrollments')
    op.drop_table('student_course_enrollments')
    # ### end Alembic commands ###
