"""add_catalog_course_id_to_subjects

Revision ID: 6c4ec519a8aa
Revises: 1db0219f8f7e
Create Date: 2026-06-21 13:54:47.065531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4ec519a8aa'
down_revision: Union[str, Sequence[str], None] = '1db0219f8f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('catalog_course_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_subjects_catalog_course_id'), 'subjects', ['catalog_course_id'], unique=False)
    op.create_foreign_key(None, 'subjects', 'courses', ['catalog_course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_index(op.f('ix_subjects_catalog_course_id'), table_name='subjects')
    op.drop_column('subjects', 'catalog_course_id')
    # ### end Alembic commands ###
