"""add_audit_logging_and_role_models

Revision ID: b42401a5c708
Revises: a8f2e3b4c567
Create Date: 2026-06-18 01:10:49.922319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b42401a5c708'
down_revision: Union[str, Sequence[str], None] = 'a8f2e3b4c567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_roles_id'), 'admin_roles', ['id'], unique=False)
    op.create_index(op.f('ix_admin_roles_name'), 'admin_roles', ['name'], unique=True)
    op.create_table('study_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_de', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_study_programs_code'), 'study_programs', ['code'], unique=True)
    op.create_index(op.f('ix_study_programs_id'), 'study_programs', ['id'], unique=False)
    op.create_index(op.f('ix_study_programs_is_deleted'), 'study_programs', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_study_programs_name'), 'study_programs', ['name'], unique=False)
    op.create_table('universities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_de', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_universities_id'), 'universities', ['id'], unique=False)
    op.create_index(op.f('ix_universities_is_deleted'), 'universities', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_universities_name'), 'universities', ['name'], unique=True)
    op.create_table('academic_tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('study_program_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_de', sa.String(length=255), nullable=True),
    sa.Column('level', sa.Enum('BACHELOR', 'MASTER', 'DOCTORATE', name='tracklevel'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('total_ects_required', sa.Integer(), nullable=False),
    sa.Column('graduation_conditions', sa.Text(), nullable=True),
    sa.Column('graduation_conditions_de', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_program_id'], ['study_programs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_academic_tracks_id'), 'academic_tracks', ['id'], unique=False)
    op.create_index(op.f('ix_academic_tracks_is_deleted'), 'academic_tracks', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_academic_tracks_level'), 'academic_tracks', ['level'], unique=False)
    op.create_index(op.f('ix_academic_tracks_name'), 'academic_tracks', ['name'], unique=False)
    op.create_index(op.f('ix_academic_tracks_study_program_id'), 'academic_tracks', ['study_program_id'], unique=False)
    op.create_table('admin_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('resource', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['admin_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_permissions_action'), 'admin_permissions', ['action'], unique=False)
    op.create_index(op.f('ix_admin_permissions_id'), 'admin_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_admin_permissions_resource'), 'admin_permissions', ['resource'], unique=False)
    op.create_index(op.f('ix_admin_permissions_role_id'), 'admin_permissions', ['role_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_operation'), 'audit_logs', ['operation'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('campuses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_de', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campuses_id'), 'campuses', ['id'], unique=False)
    op.create_index(op.f('ix_campuses_is_deleted'), 'campuses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_campuses_name'), 'campuses', ['name'], unique=False)
    op.create_index(op.f('ix_campuses_university_id'), 'campuses', ['university_id'], unique=False)
    op.create_table('university_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=False),
    sa.Column('study_program_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['study_program_id'], ['study_programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['university_id'], ['universities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_university_programs_study_program_id'), 'university_programs', ['study_program_id'], unique=False)
    op.create_index(op.f('ix_university_programs_university_id'), 'university_programs', ['university_id'], unique=False)
    op.create_table('user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('university_id', sa.Integer(), nullable=True),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('assigned_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['admin_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_roles_id'), 'user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_user_roles_program_id'), 'user_roles', ['program_id'], unique=False)
    op.create_index(op.f('ix_user_roles_role_id'), 'user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_user_roles_university_id'), 'user_roles', ['university_id'], unique=False)
    op.create_index(op.f('ix_user_roles_user_id'), 'user_roles', ['user_id'], unique=False)
    op.create_table('semesters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_track_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('name_de', sa.String(length=100), nullable=True),
    sa.Column('semester_number', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('ects_required', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_track_id'], ['academic_tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_semesters_academic_track_id'), 'semesters', ['academic_track_id'], unique=False)
    op.create_index(op.f('ix_semesters_id'), 'semesters', ['id'], unique=False)
    op.create_index(op.f('ix_semesters_is_deleted'), 'semesters', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_semesters_name'), 'semesters', ['name'], unique=False)
    op.create_table('validation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_track_id', sa.Integer(), nullable=False),
    sa.Column('rule_type', sa.Enum('SEMESTER_VALIDATION', 'YEAR_PROGRESSION', 'GRADUATION', name='ruletype'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_de', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('minimum_ects', sa.Integer(), nullable=False),
    sa.Column('additional_conditions', sa.Text(), nullable=True),
    sa.Column('additional_conditions_de', sa.Text(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_track_id'], ['academic_tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_validation_rules_academic_track_id'), 'validation_rules', ['academic_track_id'], unique=False)
    op.create_index(op.f('ix_validation_rules_id'), 'validation_rules', ['id'], unique=False)
    op.create_index(op.f('ix_validation_rules_is_deleted'), 'validation_rules', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_validation_rules_rule_type'), 'validation_rules', ['rule_type'], unique=False)
    op.create_table('teaching_units',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_de', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('ects_required', sa.Integer(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teaching_units_code'), 'teaching_units', ['code'], unique=True)
    op.create_index(op.f('ix_teaching_units_id'), 'teaching_units', ['id'], unique=False)
    op.create_index(op.f('ix_teaching_units_is_deleted'), 'teaching_units', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_teaching_units_name'), 'teaching_units', ['name'], unique=False)
    op.create_index(op.f('ix_teaching_units_semester_id'), 'teaching_units', ['semester_id'], unique=False)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('teaching_unit_id', sa.Integer(), nullable=True),
    sa.Column('semester_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('name_de', sa.String(length=255), nullable=True),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('description_de', sa.Text(), nullable=True),
    sa.Column('ects_credits', sa.Integer(), nullable=False),
    sa.Column('coefficient', sa.Float(), nullable=False),
    sa.Column('difficulty_level', sa.Integer(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['semester_id'], ['semesters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teaching_unit_id'], ['teaching_units.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.create_index(op.f('ix_courses_id'), 'courses', ['id'], unique=False)
    op.create_index(op.f('ix_courses_is_deleted'), 'courses', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_courses_name'), 'courses', ['name'], unique=False)
    op.create_index(op.f('ix_courses_semester_id'), 'courses', ['semester_id'], unique=False)
    op.create_index(op.f('ix_courses_teaching_unit_id'), 'courses', ['teaching_unit_id'], unique=False)
    op.create_table('course_prerequisites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['prerequisite_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_course_prerequisites_course_id'), 'course_prerequisites', ['course_id'], unique=False)
    op.create_index(op.f('ix_course_prerequisites_prerequisite_id'), 'course_prerequisites', ['prerequisite_id'], unique=False)
    op.drop_index('ix_constraints_user_id_active', table_name='constraints')
    op.create_index(op.f('ix_constraints_active'), 'constraints', ['active'], unique=False)
    op.create_index(op.f('ix_constraints_user_id'), 'constraints', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if separate indexes exist before dropping (they might not exist if migrating from old state)
    # Drop separate indexes only if they exist
    op.execute("DROP INDEX IF EXISTS ix_constraints_user_id")
    op.execute("DROP INDEX IF EXISTS ix_constraints_active")
    # Create composite index if it doesn't exist
    op.execute("CREATE INDEX IF NOT EXISTS ix_constraints_user_id_active ON constraints (user_id, active)")
    op.drop_index(op.f('ix_course_prerequisites_prerequisite_id'), table_name='course_prerequisites')
    op.drop_index(op.f('ix_course_prerequisites_course_id'), table_name='course_prerequisites')
    op.drop_table('course_prerequisites')
    op.drop_index(op.f('ix_courses_teaching_unit_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_semester_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_name'), table_name='courses')
    op.drop_index(op.f('ix_courses_is_deleted'), table_name='courses')
    op.drop_index(op.f('ix_courses_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_teaching_units_semester_id'), table_name='teaching_units')
    op.drop_index(op.f('ix_teaching_units_name'), table_name='teaching_units')
    op.drop_index(op.f('ix_teaching_units_is_deleted'), table_name='teaching_units')
    op.drop_index(op.f('ix_teaching_units_id'), table_name='teaching_units')
    op.drop_index(op.f('ix_teaching_units_code'), table_name='teaching_units')
    op.drop_table('teaching_units')
    op.drop_index(op.f('ix_validation_rules_rule_type'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_rules_is_deleted'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_rules_id'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_rules_academic_track_id'), table_name='validation_rules')
    op.drop_table('validation_rules')
    op.drop_index(op.f('ix_semesters_name'), table_name='semesters')
    op.drop_index(op.f('ix_semesters_is_deleted'), table_name='semesters')
    op.drop_index(op.f('ix_semesters_id'), table_name='semesters')
    op.drop_index(op.f('ix_semesters_academic_track_id'), table_name='semesters')
    op.drop_table('semesters')
    op.drop_index(op.f('ix_user_roles_user_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_university_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_role_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_program_id'), table_name='user_roles')
    op.drop_index(op.f('ix_user_roles_id'), table_name='user_roles')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_university_programs_university_id'), table_name='university_programs')
    op.drop_index(op.f('ix_university_programs_study_program_id'), table_name='university_programs')
    op.drop_table('university_programs')
    op.drop_index(op.f('ix_campuses_university_id'), table_name='campuses')
    op.drop_index(op.f('ix_campuses_name'), table_name='campuses')
    op.drop_index(op.f('ix_campuses_is_deleted'), table_name='campuses')
    op.drop_index(op.f('ix_campuses_id'), table_name='campuses')
    op.drop_table('campuses')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_operation'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_admin_permissions_role_id'), table_name='admin_permissions')
    op.drop_index(op.f('ix_admin_permissions_resource'), table_name='admin_permissions')
    op.drop_index(op.f('ix_admin_permissions_id'), table_name='admin_permissions')
    op.drop_index(op.f('ix_admin_permissions_action'), table_name='admin_permissions')
    op.drop_table('admin_permissions')
    op.drop_index(op.f('ix_academic_tracks_study_program_id'), table_name='academic_tracks')
    op.drop_index(op.f('ix_academic_tracks_name'), table_name='academic_tracks')
    op.drop_index(op.f('ix_academic_tracks_level'), table_name='academic_tracks')
    op.drop_index(op.f('ix_academic_tracks_is_deleted'), table_name='academic_tracks')
    op.drop_index(op.f('ix_academic_tracks_id'), table_name='academic_tracks')
    op.drop_table('academic_tracks')
    op.drop_index(op.f('ix_universities_name'), table_name='universities')
    op.drop_index(op.f('ix_universities_is_deleted'), table_name='universities')
    op.drop_index(op.f('ix_universities_id'), table_name='universities')
    op.drop_table('universities')
    op.drop_index(op.f('ix_study_programs_name'), table_name='study_programs')
    op.drop_index(op.f('ix_study_programs_is_deleted'), table_name='study_programs')
    op.drop_index(op.f('ix_study_programs_id'), table_name='study_programs')
    op.drop_index(op.f('ix_study_programs_code'), table_name='study_programs')
    op.drop_table('study_programs')
    op.drop_index(op.f('ix_admin_roles_name'), table_name='admin_roles')
    op.drop_index(op.f('ix_admin_roles_id'), table_name='admin_roles')
    op.drop_table('admin_roles')
    # Drop enum types
    op.execute("DROP TYPE IF EXISTS tracklevel")
    op.execute("DROP TYPE IF EXISTS ruletype")
    # ### end Alembic commands ###
